hooks:
    pre-commit:
        docs: true
        syntax: true
        flay: true
        flog: true
        reek: true
        roodi: true
        saikuro: true
        specs: true
        tests: true
    commit-msg: true
syntax:
    # regular expressions 
    ruby: (\.rb|\.rake|Gemfile|Rakefile)$
    ignore: ignore_my_syntax\.rb$
