#!/usr/bin/env ruby

require 'yaml'

config = YAML.load_file("./.git/hooks/config.yml")
errors = []

ruby_files = Dir[*config['ruby']] - Dir[*config['ignore']]

ruby_files.each do |file|
  output = %x(ruby -c #{file} 2>&1)
  errors << output unless $? == 0
end

unless errors.empty?
  puts errors
  exit 1
end